### ISSUE TITLE
Getting below error while running the app , any idea ?

### ISSUE THREAD

**Issue by sharan-nss** [RenwaX23/XSSTRON#1]
/XSSTRON/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! XSSTRON@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the XSSTRON@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by xElkomy** [comment]
I think you must run it on low privilege user

**Comment by 007divyachawla** [comment]
I am also getting same error in Kali linux. But on running the npm install as a low privilige user.

npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /home/kali/Downloads/XSSTRON/package-lock.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/home/kali/Downloads/XSSTRON/package-lock.json'
npm ERR!  [Error: EACCES: permission denied, open '/home/kali/Downloads/XSSTRON/package-lock.json'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/home/kali/Downloads/XSSTRON/package-lock.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2021-02-01T15_32_21_582Z-debug.log

Please suggest

**Comment by RenwaX23** [comment]
Hey try these hope it fixes your problem

- Try to update npm and nodejs to latest version 
- delete node_modules folder and reinstall 
- in package.json change the electron devDepencies to (electron11-bin)
- install electron using (npm install electron) and run the app with electron using (electron .)

with each step remember to delete the node_modules folder and re install again using (npm install)

**Comment by 007divyachawla** [comment]
Renwa Can u please include this step in the mail page for other people to help.

**Comment by RenwaX23** [comment]
Added, does this fixed your problem(s)?

**Comment by marz-hunter** [comment]
can this be installed on windows?

**Comment by 007divyachawla** [comment]
@RenwaX23 I have tried the steps what you mention, on running electron . it gives the following error.

electron .                                                                                                                                                             1 ⨯
[24863:0202/013633.721484:FATAL:electron_main_delegate.cc(253)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/local/lib/node_modules/electron/dist/electron exited with signal SIGTRAP

Also can you confirm which OS is best where we dont get the error, also can you mention the prerquistes for the same.Its a request.

**Comment by RenwaX23** [comment]
Hey this seems to be issue with Electron itself for now you can use on other systems Windows, OSX and Linux installed on Windows
