### ISSUE TITLE
Error while using Mass Scan 

### ISSUE THREAD

**Issue by PrajwalKhante** [RenwaX23/XSSTRON#14]
npm ERR! code 3221225477
npm ERR! path C:\Users\pra27\Desktop\XSSTRON-main
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c electron .

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pra27\AppData\Local\npm-cache\_logs\2021-02-15T17_53_05_021Z-debug.log

**Comment by RenwaX23** [comment]
try install electron using `npm install electron -g`
