### ISSUE TITLE
The website opens but the XSS found page does not open

### ISSUE THREAD

**Issue by jackwls** [RenwaX23/XSSTRON#15]
Issues: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.

**Comment by RenwaX23** [comment]
The XSS Found page open only when XSS is found, are you sure the site is vulnerable to XSS?

**Comment by jackwls** [comment]
Yes, I use this site (http://testphp.vulnweb.com) I am using Kali Linux and I keep encountering this post on my terminal: electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information. How can I fix?

**Comment by RenwaX23** [comment]
The warning about `contextIsolation` is something normal and not an error, in Kali I has some issues in meantime you can use any other OS
