### ISSUE TITLE
Getting This Error 

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [RenwaX23/XSSTRON#19]
npm start

> XSSTRON@1.0.0 start
> electron .

/home/user/XSSTRON/node_modules/electron/dist/electron exited with signal SIGSEGV

I Don't now what to do from Here ??

**Comment by RenwaX23** [comment]
Hey try install it on Windows OS

**Comment by aviadhahami** [comment]
@Deku-izuku-dotcom see https://github.com/RenwaX23/XSSTRON/issues/3
