### ISSUE TITLE
Unable to start project both in linux and windows

### ISSUE THREAD

**Issue by UnShUGo** [RenwaX23/XSSTRON#5]
C:\Users\......\Documents\My_list\XSSTRON>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\.........\Documents\My_list\XSSTRON\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\...........\Documents\My_list\XSSTRON\package.json'
npm WARN XSSTRON No description
npm WARN XSSTRON No repository field.
npm WARN XSSTRON No README data
npm WARN XSSTRON No license field.

up to date in 0.396s
found 0 vulnerabilities

C:\Users\........\Documents\My_list\XSSTRON>npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\.....\Documents\My_list\XSSTRON\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\.......\Documents\My_list\XSSTRON\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\.........\AppData\Roaming\npm-cache\_logs\2021-02-03T06_41_20_529Z-debug.log

> XSSTRON@1.0.0 start
> electron .

[1865:0203/014611.704918:FATAL:electron_main_delegate.cc(254)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/root/XSSTRON/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code 1
npm ERR! path /root/XSSTRON
npm ERR! command failed
npm ERR! command sh -c electron .

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-03T06_46_11_722Z-debug.log

**Comment by RenwaX23** [comment]
sorry to hear that if you were able to run it tell me, for windows no one had issues before

**Comment by fropert** [comment]
Run **npm start** as a user, not as root

**Comment by devcoinfet** [comment]
yes but there are other errors we may need to help with 

if you get access denied after using sudo to install the tool

npm install -g electron --unsafe-perm=true --allow-root


if you also get another error about sandbox do this

cd pathto/sandbox
sudo chown root:root chrome-sandbox
sudo chmod 4755 chrome-sandbox

than like fropert says do not run the npm start wtih root it works on kali the muppets rejoice :)

**Comment by RenwaX23** [comment]
Thanks i have added it

**Comment by mouseglove** [comment]
I had the same issue, although as non-root:
/root/XSSTRON/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code 1
npm ERR! path /root/XSSTRON
npm ERR! command failed
npm ERR! command sh -c electron .

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-02-03T06_46_11_722Z-debug.log

I was able to get it to launch, by navigating to the path, and running: 
electron ./

seems ok so far
